config/routes.rb
Microforum::Application.routes.draw do
  resources :topics  do
    resources :replies
  end

  devise_for :users

  get "home/index"
  get "home/init"
  root :to=>'topics#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topics

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  validates_presence_of :content

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :replies,:dependent=>:destroy
  validates_presence_of :title
  validates_presence_of :content
  self.per_page = 20
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:username
  validates_presence_of :username
  has_many :topics
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_local
  protected
  def set_local

     if params[:locale]&&["en","zh_cn"].include?(params[:locale])

         session[:locale]=params[:locale]

     end

     I18n.locale = session[:locale]||I18n.default_locale

  end
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'scaluo' && password == 'bg3721_monkey'
    end
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate,:except => [:index]
  def index
  end

  def init
    Category.create(:name=>'C# & .NET')
    Category.create(:name=>'JavaScript')
    Category.create(:name=>'CSS & XHTML')
    Category.create(:name=>'Ruby')
    Category.create(:name=>'Ruby ON Rails')
    redirect_to root_path
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @topic = Topic.find(params[:topic_id])
    @reply = @topic.replies.build(params[:reply])
    @reply.user = current_user
    if @reply.save
      redirect_to topic_path(@topic)
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
	  @reply=@topic.replies.find(params[:id])
  	@reply.destroy
	  redirect_to topic_path(@topic)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!,only: [:new,:create,:update,:destroy,:edit]
  before_filter :only_my_topic,only: [:update,:destroy,:edit]
  before_filter :get_categories
  layout 'topic'
  # GET /topics
  # GET /topics.json
  def index

    if params[:category_id]
      @topics = Topic.where(:category_id =>params[:category_id]).order('id desc').paginate(:page => params[:page])
    else
     # @posts = Post.paginate(:page => params[:page])
      @topics = Topic.order('id desc').paginate(:page => params[:page])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit

  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.build(params[:topic])


    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update


    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy

    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :ok }
    end
  end

  protected
  def only_my_topic
    @topic = current_user.topics.find(params[:id])
  end

  def get_categories
   @categories = Category.order("name")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title (*parts)
    unless parts.empty?
      content_for :title do
        (parts<<"Micro Forum").join("-")  unless parts.empty?
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def category_options(categories)
    categories.map{|c|[c.name,c.id]}
  end
end

app/views/categories/_category.html.erb
<li><%=link_to category.name,topics_path(:category_id=>category.id) %></li>

app/views/home/index.html.erb
<%=link_to 'init',:controller=>'home',:action => 'init'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%=render :partial=>'share/title' %>

  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
   <div id="brand">
     <div id="logo"><%=t(:logo)%></div>
     <div id="topnav">
       <%=render :partial=>'share/nav' %>
     </div>
   </div>
   <div id="content1">
     <%=render :partial=>'share/notice'%>
     <%= yield %>
   </div>
   <div id="footer"><hr/><%=render :partial=>'share/foot'%></div>
</div>
</body>
</html>

app/views/layouts/topic.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=render :partial=>'share/title' %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
  <div id="brand">
    <div id="logo"><%=t(:logo)%></div>
    <div id="topnav">
      <%=render :partial=>'share/nav' %>

     </div>
  </div>
  <div id="content">

    <%=render :partial=>'share/notice' %>
    <%= yield %>
  </div>
   <div id="nav">
      <div class="navblock">
      <%if @categories -%>
      <ul>
        <li><%=link_to 'All',topics_path %></li>
        <%=render :partial =>'categories/category',:collection=>@categories %>
      </ul>
      <% end -%>
      </div>
  </div>
   <div id="footer"><hr/><%=render :partial=>'share/foot'%></div>
</div>
</body>
</html>

app/views/replies/_form.html.erb
<%=form_for([@topic,@topic.replies.build]) do |f|%>
  <p>

	<%=f.text_area :content%><br/>
  </p>
  <div class="actions">
    <%=f.submit t(:post_reply)%>
  </div>
<%end%>

app/views/replies/_reply.html.erb
<div class="postsbox">
  <div class="postsinfo"><%=t(:posted_by)%> <%= reply.user.username %> <%=t(:posted_on)%> <%=reply.created_at.to_date%></div>
  <div class="postscontent"><%= simple_format reply.content %></div>
  <%if user_signed_in? && current_user==reply.user%>
  <div class="postsfoot">
     <%= link_to t(:delete), [reply.topic,reply],:method=>:delete,:confirm=>t(:delete_confirm)%>
  </div>
  <% end %>
</div>

app/views/share/_foot.html.erb
<%=t(:choose_lan)%>:<%=link_to "English",:controller=>controller.controller_name,:action=>controller.action_name,:locale=>"en"%>
<%=link_to "简体中文",:controller=>controller.controller_name,:action=>controller.action_name,:locale=>"zh_cn" %>

app/views/share/_nav.html.erb
<%=link_to t(:home),root_path%> |
      <% if user_signed_in?  %>
        <%=link_to t(:new_topic),new_topic_path%> |
        <%=current_user.username%> |
        <%=link_to t(:login_out),destroy_user_session_path,:method=>'delete'%>
      <% else %>
        <%=link_to t(:register),new_user_registration_path%> |
        <%=link_to t(:login),new_user_session_path%>
      <% end %>

app/views/share/_notice.html.erb
 <%if flash[:notice]%>
    <p id="notice"><%=flash[:notice]%></p>
<%end %>
<%if flash[:warning]%>
    <p id="alert"><%=flash[:alert]%></p>
<%end%>

app/views/share/_title.html.erb
<%if content_for?(:title) %>
       <%=yield(:title) %>
<% else %>
       Micro Forum
<% end %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title,t(:title) %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category,t(:category) %><br />
    <%= f.select :category_id,category_options(@categories) %>
  </div>
  <div class="field">
    <%= f.label :content,t(:content) %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit t(:submit)%>
  </div>

<% end %>

app/views/topics/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
 <table class="list">
  <tr class="headrow">
    <th class="tdtitle"><%=t(:title)%></th>
    <th class="tdauthor"><%=t(:author)%></th>
    <th class="tdreplies"><%=t(:replies)%></th>
    <th class="tdposttime"><%=t(:post_time)%></th>
  </tr>
<% @topics.each do |topic| %>
  <tr class="<%=cycle('list-line-odd', 'list-line-even') %>">
    <td class="tdtitle"><%=link_to topic.title,topic %></td>
    <td class="tdauthor"><%= topic.user.username%></td>
    <td class="tdreplies"><%= topic.replies.count %></td>
    <td class="tdposttime"><%= topic.created_at.to_date %></td>
  </tr>
<% end %>
</table>
<div class="dvpage"><%= will_paginate @topics,:previous_label=>t(:page_previous),:next_label=>t(:page_next) %></div>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/show.html.erb
<% title(@topic.title)%>
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<div class="postsbox">
  <div class="poststitle"><%= @topic.title %></div>
  <div class="postsinfo"><%=t(:posted_by)%> <%= @topic.user.username %> <%=t(:posted_on)%>  <%=@topic.created_at.to_date%>--------------<%=link_to @topic.category.name,topics_path(:category_id=>@topic.category.id) %></div>
  <div class="postscontent"><%= simple_format @topic.content %></div>
  <%if user_signed_in? && current_user==@topic.user%>
  <div class="postsfoot"><%= link_to t(:edit), edit_topic_path(@topic) %> |
     <%= link_to t(:delete), topic_path(@topic),:method=>:delete,:confirm=>t(:delete_confirm)%>
  </div>
  <% end %>
</div>
<%=render :partial => 'replies/reply',:collection => @topic.replies%>
<div class="postsbox">
  <p class="title"><%=t(:post_reply)%></p>
 <%if user_signed_in?%>

   <%=render :partial => 'replies/form'%>
 <%else%>
   <p> <%=t(:please_login)%> </p>
 <%end%>
 </div>